add: package verify

diff --git a/tool/ssinstall b/tool/ssinstall
--- a/tool/ssinstall
+++ b/tool/ssinstall
@@ -1,5 +1,6 @@
 #!/bin/bash
-
+SPARK_DOWNLOAD_SERVER_URL="http://127.0.0.1:8000"
+SPARK_DOWNLOAD_SERVER_URL_NO_PROTOCOL="127.0.0.1:8000"
 source /opt/durapps/spark-store/bin/bashimport/transhell.amber
 load_transhell_debug
 
@@ -56,6 +57,33 @@ function zenity() {
     sudo -u "$user" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$uid"/bus zenity "$@"
 }
 
+function hash_check() {
+    if [ ! -e "/var/lib/aptss/lists/${SPARK_DOWNLOAD_SERVER_URL_NO_PROTOCOL}_${STORE_URL}_Packages" ] && \
+       [ ! -e "/var/lib/aptss/lists/d.store.deepinos.org.cn_${STORE_URL}_Packages" ] && \
+       [ ! -e "/var/lib/aptss/lists/mirrors.sdu.edu.cn_spark-store-repository_${STORE_URL}_Packages" ]; then
+        echo "接收星火仓库软件信息中..."
+        aptss ssupdate
+    fi
+
+    if [ -e "/var/lib/aptss/lists/${SPARK_DOWNLOAD_SERVER_URL_NO_PROTOCOL}_${STORE_URL}_Packages" ]; then
+        PACKAGES_DATA_PATH="/var/lib/aptss/lists/${SPARK_DOWNLOAD_SERVER_URL_NO_PROTOCOL}_${STORE_URL}_Packages"
+        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是星火域名仓库配置"
+    elif [ -e "/var/lib/aptss/lists/d.store.deepinos.org.cn_${STORE_URL}_Packages" ]; then
+        PACKAGES_DATA_PATH="/var/lib/aptss/lists/d.store.deepinos.org.cn_${STORE_URL}_Packages"
+        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是d域名单目录仓库配置"
+    else
+        PACKAGES_DATA_PATH="/var/lib/aptss/lists/mirrors.sdu.edu.cn_spark-store-repository_${STORE_URL}_Packages"
+        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是SDU镜像仓库配置"
+    fi
+
+    echo "正在运行包验证..."
+    echo "Running Spark Package Verify..."
+
+    DEB_SHA512SUM=$(sha512sum "$1" | cut -d ' ' -f 1)
+    unset IS_SHA512SUM_CHECKED
+    IS_SHA512SUM_CHECKED=$(cat "$PACKAGES_DATA_PATH" | grep "$DEB_SHA512SUM")
+}
+
 
 
 ####################################
@@ -81,9 +109,22 @@ fi
 
 DEBPATH=$(realpath "$1")
 
+hash_check "$DEBPATH"
 
+if [ -z "$IS_SHA512SUM_CHECKED" ]; then
+    echo "尝试更新仓库信息重新校验"
+    aptss ssupdate
+    hash_check "$DEBPATH"
+	if [ -z "$IS_SHA512SUM_CHECKED" ]; then
+	echo -e "$TRANSHELL_CONTENT_HASH_CHECK_FAILED"
+	zenity --info --icon-name=spark-store --height 270 --width 500 --text "$TRANSHELL_CONTENT_HASH_CHECK_FAILED"
+	echo  "OMG-IT-GOES-WRONG"
+	exit 1
+	fi
+fi
 
-    echo "定制版跳过校验，开始安装"
+if [ ! -z "$IS_SHA512SUM_CHECKED" ]; then
+    echo "校验成功，开始安装"
     echo "----------------------------------------------------------------------------------"
     package_name=$(dpkg-deb -f "$DEBPATH" Package)
     echo "Package name is $package_name"
@@ -126,3 +167,5 @@ DEBPATH=$(realpath "$1")
             echo "OMG-IT-GOES-WRONG"
         fi
     fi
+fi
+
